# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/sd-card/sd-image-armv7l-multiplatform-installer.nix")
    #(modulesPath + "/installer/sd-card/sd-image-raspberrypi.nix")
    #(modulesPath + "/installer/scan/not-detected.nix")
    #inputs.nixos-hardware.nixosModules.raspberry-pi-2
  ];
  hardware.enableAllHardware = false;

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/NIXOS_SD";
      fsType = "ext4";
      options = [ "noatime" ];
    };
  };

  boot.supportedFilesystems.zfs = lib.mkForce false;
  boot.kernelPackages = lib.mkForce pkgs.linuxKernel.packages.linux_rpi2;
  #sdImage.compressImage = false;

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkForce "armv7l-linux";
}
