# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  inputs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/sd-card/sd-image-aarch64.nix")
    #(modulesPath + "/installer/scan/not-detected.nix")
    inputs.nixos-hardware.nixosModules.raspberry-pi-4
  ];
  #hardware.enableAllHardware = lib. false;
  boot = {
    initrd = {
      # availableKernelModules = {
      #   xhci_pci = true;
      #   usbhid = true;
      #   dw-hdmi = lib.mkForce false;
      #   dw-mipi-dsi = lib.mkForce false;
      #   rockchipdrm = lib.mkForce false;
      #   rockchip-rga = lib.mkForce false;
      #   phy-rockchip-pcie = lib.mkForce false;
      #   pcie-rockchip-host = lib.mkForce false;
      #   pwm-sun4i = lib.mkForce false;
      #   sun4i-drm = lib.mkForce false;
      #   sun8i-mixer = lib.mkForce false;
      # };
      kernelModules = [ ];
      allowMissingModules = true;
    };
    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  # fileSystems."/" = {
  #   device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
  #   fsType = "ext4";
  # };

  boot.supportedFilesystems.zfs = lib.mkForce false;
  sdImage.compressImage = false;

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkForce "aarch64-linux";
}
